/**
 * Compact glossary of the course terms. Each entry: Persian term, English term, one-line meaning.
 */
export const GLOSSARY = [
  { term: 'بار الکتریکی', en: 'electric charge', meaning: String.raw`خاصیت ذاتی پروتون و الکترون؛ پروتون مثبت و الکترون منفی در نظر گرفته می‌شود.` },
  { term: 'بار بنیادی', en: 'elementary charge', meaning: String.raw`کوچک‌ترین واحد بار: $e = 1.602\\times10^{-19}\\,\\text{C}$.` },
  { term: 'رسانا', en: 'conductor', meaning: String.raw`ماده‌ای که بار در آن می‌تواند آزادانه جابه‌جا شود؛ مثل فلزات.` },
  { term: 'نیمه‌رسانا', en: 'semiconductor', meaning: String.raw`ماده‌ای بین رسانا و عایق که با ناخالصی یا دما هدایتش زیاد می‌شود؛ مثل سیلیسیم.` },
  { term: 'عایق', en: 'insulator', meaning: String.raw`ماده‌ای که بار در آن قفل است و عبور نمی‌کند؛ مثل شیشه و پلاستیک.` },
  { term: 'بقای بار', en: 'charge conservation', meaning: String.raw`بار کل یک سیستم منزوی ثابت می‌ماند؛ بار ساخته یا نابود نمی‌شود.` },
  { term: 'کوانتش بار', en: 'charge quantization', meaning: String.raw`بار هر جسم مضربی صحیح از بار بنیادی است: $q = ne$.` },
  { term: 'قانون کولن', en: "Coulomb's law", meaning: String.raw`نیروی بین دو بار نقطه‌ای: $F = k|q_1q_2|/r^2$.` },
  { term: 'ثابت کولن', en: 'Coulomb constant', meaning: String.raw`$k = 8.99\\times10^{9}\\,\\text{N·m}^2/\\text{C}^2$.` },
  { term: 'گذردهی خلأ', en: 'vacuum permittivity', meaning: String.raw`$\\varepsilon_0 = 8.85\\times10^{-12}\\,\\text{C}^2/(\\text{N·m}^2)$.` },
  { term: 'برهم‌نهی', en: 'superposition', meaning: String.raw`جمع کردن اثر منابع مختلف؛ برای نیرو و میدان **برداری** و برای پتانسیل **جبری** است.` },
  { term: 'میدان الکتریکی', en: 'electric field', meaning: String.raw`کمیت برداری ویژگی محیط که نیرو بر بار آزمایشی را تعیین می‌کند: $\\vec E = \\vec F/q_0$.` },
  { term: 'بار آزمایشی', en: 'test charge', meaning: String.raw`بار مثبت و کوچکی که برای اندازه‌گیری میدان در یک نقطه قرار می‌دهیم.` },
  { term: 'دوقطبی', en: 'electric dipole', meaning: String.raw`دو بار مخالف با فاصله‌ی کم؛ با بردار $p = qd$ توصیف می‌شود.` },
  { term: 'پتانسیل الکتریکی', en: 'electric potential', meaning: String.raw`انرژی پتانسیل بر واحد بار؛ کمیتی نرده‌ای که با $1/r$ کم می‌شود.` },
  { term: 'اختلاف پتانسیل', en: 'potential difference', meaning: String.raw`کار میدان بر واحد بار بین دو نقطه: $V_B - V_A = -\\int \\vec E\\cdot d\\vec s$.` },
  { term: 'ولت', en: 'volt', meaning: String.raw`واحد پتانسیل؛ برابر ژول بر کولن.` },
  { term: 'شیب پتانسیل', en: 'gradient of V', meaning: String.raw`رابطه‌ی میدان و پتانسیل: $\\vec E = -\\nabla V$.` },
  { term: 'چگالی خطی بار', en: 'linear charge density', meaning: String.raw`$\\lambda = Q/L$ برای بار روی یک خط یا سیم.` },
  { term: 'چگالی سطحی بار', en: 'surface charge density', meaning: String.raw`$\\sigma = Q/A$ برای بار روی یک سطح.` },
  { term: 'چگالی حجمی بار', en: 'volume charge density', meaning: String.raw`$\\rho = Q/V$ برای بار توزیع‌شده در حجم.` },
  { term: 'شار الکتریکی', en: 'electric flux', meaning: String.raw`میزان عبور میدان از یک سطح: $\\Phi_E = \\int \\vec E\\cdot d\\vec A$.` },
  { term: 'قانون گاوس', en: "Gauss's law", meaning: String.raw`$\\Phi_E = q_{net}/\\varepsilon_0$: شار فقط به بار داخل سطح بستگی دارد.` },
  { term: 'سطح گاوسی', en: 'Gaussian surface', meaning: String.raw`سطح فرضی بسته که با تقارن آرایش انتخاب می‌شود تا محاسبه آسان شود.` },
  { term: 'خازن', en: 'capacitor', meaning: String.raw`وسیله‌ی ذخیره‌ی بار و انرژی الکتریکی با دو رسانا و یک عایق.` },
  { term: 'ظرفیت', en: 'capacitance', meaning: String.raw`$C = Q/V$؛ ویژگی هندسی خازن، مستقل از بار و ولتاژ.` },
  { term: 'فاراد', en: 'farad', meaning: String.raw`واحد ظرفیت؛ خازنی که با یک ولت یک کولن بار ذخیره می‌کند.` },
  { term: 'دی‌الکتریک', en: 'dielectric', meaning: String.raw`ماده‌ای نارسا که با قطبی شدن، ظرفیت خازن را با ضریب $\\kappa$ زیاد می‌کند.` },
  { term: 'انرژی ذخیره‌شده', en: 'stored energy', meaning: String.raw`$U = \\tfrac12 CV^2$ در خازن.` },
  { term: 'جریان الکتریکی', en: 'electric current', meaning: String.raw`نرخ عبور بار از یک سطح: $I = dQ/dt$، با واحد آمپر.` },
  { term: 'سرعت رانشی', en: 'drift velocity', meaning: String.raw`مؤلفه‌ی بسیار کوچکی از سرعت الکترون در راستای میدان.` },
  { term: 'چگالی جریان', en: 'current density', meaning: String.raw`$J = I/A$ و رابطه‌ی $J = nqv_d$.` },
  { term: 'مقاومت', en: 'resistance', meaning: String.raw`$R = V/I$، با واحد اهم.` },
  { term: 'قانون اهم', en: "Ohm's law", meaning: String.raw`برای رسانای اهمی $V = IR$ و نمودار خطی.` },
  { term: 'مقاومت ویژه', en: 'resistivity', meaning: String.raw`$\\rho$ در $R = \\rho L/A$؛ ویژگی سیم که به ماده بستگی دارد.` },
  { term: 'توان الکتریکی', en: 'electric power', meaning: String.raw`انرژی در واحد زمان: $P = VI = I^2R = V^2/R$، با واحد وات.` },
  { term: 'نیروی محرکه', en: 'emf', meaning: String.raw`$\\varepsilon = W/q$: انرژی باتری به ازای واحد بار.` },
  { term: 'مقاومت داخلی', en: 'internal resistance', meaning: String.raw`مقاومت درونی باتری که باعث $V = \\varepsilon - Ir$ می‌شود.` },
  { term: 'قوانین کیرشهف', en: "Kirchhoff's rules", meaning: String.raw`قانون گره ($\\sum I = 0$) و قانون حلقه ($\\sum \\Delta V = 0$).` },
  { term: 'ثابت زمانی', en: 'time constant', meaning: String.raw`$\\tau = RC$؛ در این زمان حدود ۶۳٪ شارژ انجام می‌شود.` },
  { term: 'میدان مغناطیسی', en: 'magnetic field', meaning: String.raw`میدانی که بر بارهای **متحرک** و جریان‌ها نیرو وارد می‌کند، با واحد تِسلا.` },
  { term: 'نیروی لورنتز', en: 'Lorentz force', meaning: String.raw`$\\vec F = q\\vec v\\times\\vec B$ روی بار متحرک؛ همیشه بر سرعت عمود است.` },
  { term: 'قاعده دست راست', en: 'right-hand rule', meaning: String.raw`انگشتان در جهت سرعت، انگشت اشاره در جهت میدان، شست در جهت نیروی بار مثبت.` },
  { term: 'شعاع مسیر', en: 'cyclotron radius', meaning: String.raw`$r = mv/qB$ برای حرکت دایره‌ای در میان مغناطیسی.` },
  { term: 'دوره‌ی سیکلوترون', en: 'cyclotron period', meaning: String.raw`$T = 2\\pi m/qB$؛ مستقل از سرعت و شعاع.` },
  { term: 'حرکت مارپیچی', en: 'helical motion', meaning: String.raw`ترکیب حرکت دایره‌ای (مؤلفه‌ی عمود) و مستقیم (مؤلفه‌ی موازی).` },
  { term: 'گشتاور مغناطیسی', en: 'magnetic torque', meaning: String.raw`$\\tau = NIAB\\sin\\theta$ و گشتاور مغناطیسی $\\mu = NIA$.` },
  { term: 'بیو-ساوار', en: 'Biot–Savart law', meaning: String.raw`ساخت میدان مغناطیسی از المان‌های جریان.` },
  { term: 'ثابت مغناطیسی', en: 'permeability of free space', meaning: String.raw`$\\mu_0 = 4\\pi\\times10^{-7}\\,\\text{T·m/A}$.` },
  { term: 'قانون آمپر', en: "Ampère's law", meaning: String.raw`$\\oint \\vec B\\cdot d\\vec l = \\mu_0 I_{enc}$.` },
  { term: 'سلونوئید', en: 'solenoid', meaning: String.raw`سیم‌پیچ بلند با میدان یکنواخت داخل و نزدیک صفر بیرون: $B = \\mu_0 nI$.` },
];